// Generated by CoffeeScript 1.6.1
(function() {
  var data, fs, render;

  fs = require('fs');

  render = require('../index').render;

  data = {
    title: 'Matrix'
  };

  render('./matrix.tex', data, function(err, rs) {
    var ws;
    if (err) {
      console.log(err);
      return console.log(rs);
    } else {
      ws = fs.createWriteStream('./output.pdf');
      return rs.pipe(ws);
    }
  });

}).call(this);
